// Generated by gencpp from file controller/instruction.msg
// DO NOT EDIT!


#ifndef CONTROLLER_MESSAGE_INSTRUCTION_H
#define CONTROLLER_MESSAGE_INSTRUCTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controller
{
template <class ContainerAllocator>
struct instruction_
{
  typedef instruction_<ContainerAllocator> Type;

  instruction_()
    : direction()
    , speed(0.0)  {
    }
  instruction_(const ContainerAllocator& _alloc)
    : direction(_alloc)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _direction_type;
  _direction_type direction;

   typedef double _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::controller::instruction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controller::instruction_<ContainerAllocator> const> ConstPtr;

}; // struct instruction_

typedef ::controller::instruction_<std::allocator<void> > instruction;

typedef boost::shared_ptr< ::controller::instruction > instructionPtr;
typedef boost::shared_ptr< ::controller::instruction const> instructionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controller::instruction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controller::instruction_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controller::instruction_<ContainerAllocator1> & lhs, const ::controller::instruction_<ContainerAllocator2> & rhs)
{
  return lhs.direction == rhs.direction &&
    lhs.speed == rhs.speed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controller::instruction_<ContainerAllocator1> & lhs, const ::controller::instruction_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controller::instruction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controller::instruction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::instruction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controller::instruction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::instruction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controller::instruction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controller::instruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "573077274c1fe00a9fd9be74da89ee17";
  }

  static const char* value(const ::controller::instruction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x573077274c1fe00aULL;
  static const uint64_t static_value2 = 0x9fd9be74da89ee17ULL;
};

template<class ContainerAllocator>
struct DataType< ::controller::instruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controller/instruction";
  }

  static const char* value(const ::controller::instruction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controller::instruction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string direction\n"
"float64 speed\n"
;
  }

  static const char* value(const ::controller::instruction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controller::instruction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.direction);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct instruction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controller::instruction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controller::instruction_<ContainerAllocator>& v)
  {
    s << indent << "direction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.direction);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLLER_MESSAGE_INSTRUCTION_H
